jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4